import { ZodiacSignInfo } from '../../types/horoscope';

export const ZODIAC_SIGNS: Omit<ZodiacSignInfo, 'prediction' | 'luckyNumber' | 'luckyColor' | 'compatibility' | 'focusArea'>[] = [
  {
    id: 'aries',
    name: 'Aries',
    rashiMarathi: 'मेष',
    rashiTranslit: 'Mesh',
    dateRange: 'Mar 21 - Apr 19',
    element: 'Fire',
    rulingPlanet: 'Mars (मंगळ)',
    symbol: '♈',
  },
  {
    id: 'taurus',
    name: 'Taurus',
    rashiMarathi: 'वृषभ',
    rashiTranslit: 'Vrishabh',
    dateRange: 'Apr 20 - May 20',
    element: 'Earth',
    rulingPlanet: 'Venus (शुक्र)',
    symbol: '♉',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    rashiMarathi: 'मिथुन',
    rashiTranslit: 'Mithun',
    dateRange: 'May 21 - Jun 20',
    element: 'Air',
    rulingPlanet: 'Mercury (बुध)',
    symbol: '♊',
  },
  {
    id: 'cancer',
    name: 'Cancer',
    rashiMarathi: 'कर्क',
    rashiTranslit: 'Kark',
    dateRange: 'Jun 21 - Jul 22',
    element: 'Water',
    rulingPlanet: 'Moon (चंद्र)',
    symbol: '♋',
  },
  {
    id: 'leo',
    name: 'Leo',
    rashiMarathi: 'सिंह',
    rashiTranslit: 'Simha',
    dateRange: 'Jul 23 - Aug 22',
    element: 'Fire',
    rulingPlanet: 'Sun (सूर्य)',
    symbol: '♌',
  },
  {
    id: 'virgo',
    name: 'Virgo',
    rashiMarathi: 'कन्या',
    rashiTranslit: 'Kanya',
    dateRange: 'Aug 23 - Sep 22',
    element: 'Earth',
    rulingPlanet: 'Mercury (बुध)',
    symbol: '♍',
  },
  {
    id: 'libra',
    name: 'Libra',
    rashiMarathi: 'तुला',
    rashiTranslit: 'Tula',
    dateRange: 'Sep 23 - Oct 22',
    element: 'Air',
    rulingPlanet: 'Venus (शुक्र)',
    symbol: '♎',
  },
  {
    id: 'scorpio',
    name: 'Scorpio',
    rashiMarathi: 'वृश्चिक',
    rashiTranslit: 'Vrishchik',
    dateRange: 'Oct 23 - Nov 21',
    element: 'Water',
    rulingPlanet: 'Mars / Pluto (मंगळ)',
    symbol: '♏',
  },
  {
    id: 'sagittarius',
    name: 'Sagittarius',
    rashiMarathi: 'धनु',
    rashiTranslit: 'Dhanu',
    dateRange: 'Nov 22 - Dec 21',
    element: 'Fire',
    rulingPlanet: 'Jupiter (गुरु)',
    symbol: '♐',
  },
  {
    id: 'capricorn',
    name: 'Capricorn',
    rashiMarathi: 'मकर',
    rashiTranslit: 'Makar',
    dateRange: 'Dec 22 - Jan 19',
    element: 'Earth',
    rulingPlanet: 'Saturn (शनी)',
    symbol: '♑',
  },
  {
    id: 'aquarius',
    name: 'Aquarius',
    rashiMarathi: 'कुंभ',
    rashiTranslit: 'Kumbh',
    dateRange: 'Jan 20 - Feb 18',
    element: 'Air',
    rulingPlanet: 'Saturn / Uranus (शनी)',
    symbol: '♒',
  },
  {
    id: 'pisces',
    name: 'Pisces',
    rashiMarathi: 'मीन',
    rashiTranslit: 'Meen',
    dateRange: 'Feb 19 - Mar 20',
    element: 'Water',
    rulingPlanet: 'Jupiter / Neptune (गुरु)',
    symbol: '♓',
  },
];

const DAILY_INSIGHTS: Record<string, { prediction: string; focus: string; color: string; number: number; match: string }> = {
  aries: {
    prediction: 'Mars amplifies initiative and decisive thinking today. Excellent time for initiating technical architectures and clearing lingering blockers.',
    focus: 'Strategic Execution & Focus',
    color: 'Crimson Red',
    number: 9,
    match: 'Leo & Sagittarius',
  },
  taurus: {
    prediction: 'Venus provides steady endurance and practical clarity. Ground your work in solid foundations and avoid hasty alterations.',
    focus: 'Stability & System Resilience',
    color: 'Forest Emerald',
    number: 6,
    match: 'Virgo & Capricorn',
  },
  gemini: {
    prediction: 'Mercury sharpens multi-threading cognitive abilities. High bandwidth for knowledge synthesis, documentation, and networking.',
    focus: 'Communication & Knowledge Synthesis',
    color: 'Electric Yellow',
    number: 5,
    match: 'Libra & Aquarius',
  },
  cancer: {
    prediction: 'The Moon heightens intuitive foresight. Protect your creative focus and trust patterns you have identified over time.',
    focus: 'Intuition & Flow State',
    color: 'Silver White',
    number: 2,
    match: 'Scorpio & Pisces',
  },
  leo: {
    prediction: 'Solar radiance highlights leadership and vision. Guide team milestones or tackle complex projects requiring bold creative direction.',
    focus: 'Vision & Architecture',
    color: 'Solar Gold',
    number: 1,
    match: 'Aries & Sagittarius',
  },
  virgo: {
    prediction: 'Analytical precision is at peak efficiency. Superb day for code refactoring, system optimization, and detail-oriented bug hunts.',
    focus: 'Optimization & Code Quality',
    color: 'Sage Green',
    number: 5,
    match: 'Taurus & Capricorn',
  },
  libra: {
    prediction: 'Harmonious planetary alignment brings balance between rapid velocity and structural integrity. Great for collaborative discussions.',
    focus: 'Equilibrium & UX Polish',
    color: 'Sky Cyan',
    number: 6,
    match: 'Gemini & Aquarius',
  },
  scorpio: {
    prediction: 'Intense investigative focus reveals hidden insights. Ideal for deep debugging, cybersecurity analysis, and resolving complex edge cases.',
    focus: 'Deep Investigation & Security',
    color: 'Deep Obsidian',
    number: 8,
    match: 'Cancer & Pisces',
  },
  sagittarius: {
    prediction: 'Expansive Jupiter inspires exploration of modern technologies and unfamiliar frameworks. Broaden your mental horizon.',
    focus: 'Exploration & Modern Tech',
    color: 'Royal Violet',
    number: 3,
    match: 'Aries & Leo',
  },
  capricorn: {
    prediction: 'Saturn rewards disciplined consistency and long-term planning. Focus on persistent durability and rock-solid architecture.',
    focus: 'Discipline & Longevity',
    color: 'Steel Charcoal',
    number: 8,
    match: 'Taurus & Virgo',
  },
  aquarius: {
    prediction: 'Original unorthodox ideas flourish today. Break out of conventional patterns with inventive local-first solutions.',
    focus: 'Innovation & Open Source',
    color: 'Neon Electric Blue',
    number: 4,
    match: 'Gemini & Libra',
  },
  pisces: {
    prediction: 'Creative synthesis merges logic with aesthetic elegance. Ideal for designing smooth interfaces and intuitive user experiences.',
    focus: 'Aesthetic Design & Empathy',
    color: 'Aquamarine',
    number: 7,
    match: 'Cancer & Scorpio',
  },
};

export function getHoroscopeDetails(signId?: string): ZodiacSignInfo[] {
  return ZODIAC_SIGNS.map(sign => {
    const detail = DAILY_INSIGHTS[sign.id] || {
      prediction: 'A balanced day with steady potential and productive energy.',
      focus: 'Productivity',
      color: 'Emerald',
      number: 7,
      match: 'All',
    };
    return {
      ...sign,
      prediction: detail.prediction,
      luckyNumber: detail.number,
      luckyColor: detail.color,
      compatibility: detail.match,
      focusArea: detail.focus,
    };
  }).filter(s => !signId || s.id === signId);
}
